name: Deploy 01-accordion

on:
  push:
    paths:
      - '01-accordion/**'
      - '.github/workflows/deploy-accordion.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 01-accordion

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./01-accordion/build
          destination_dir: 01-accordion
